import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Mono, Doto } from "next/font/google";
import "./globals.css";
import CanvasRoot from "@/components/webgl/CanvasRoot";
import LenisProvider from "@/components/dom/LenisProvider";
import VhsOverlay from "@/components/webgl/VhsOverlay";

const plexSans = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700'],
  variable: '--font-sans'
})
const plexMono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['300', '400', '500'],
  variable: '--font-mono'
})
const doto = Doto({
  subsets: ['latin'],
  variable: '--font-doto'
})

export const metadata: Metadata = {
  title: "Speculative Future Memories",
  description: "Generated by create next app",
};

import Footer from "@/components/ui/Footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${plexSans.variable} ${plexMono.variable} ${doto.variable} antialiased`}
      >
        <CanvasRoot />
        <LenisProvider>
          <div className="relative w-full mx-auto min-h-screen inset-0 pointer-events-none">
            {children}
          </div>
          <Footer />
        </LenisProvider>
        <VhsOverlay />
      </body>
    </html>
  );
}
