import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Mono, Doto } from "next/font/google";
import "./globals.css";
import CanvasRoot from "@/components/webgl/CanvasRoot";
import LenisProvider from "@/components/dom/LenisProvider";
import VhsOverlay from "@/components/webgl/VhsOverlay";

const sans = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--sans'
})
const mono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: '400',
  variable: '--mono'
})
const doto = Doto({
  subsets: ['latin'],
  variable: '--doto'
})

export const metadata: Metadata = {
  title: "Speculative Future Memories",
  description: "Generated by create next app",
};

import Footer from "@/components/ui/Footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sans.variable} ${mono.variable} ${doto.variable} antialiased`}
      >
        <CanvasRoot />
        <LenisProvider>
          <div className="relative min-h-screen">
            {children}
          </div>
          <Footer />
        </LenisProvider>
        <VhsOverlay />
      </body>
    </html>
  );
}
